### ISSUE TITLE
"exclude" vm's name with wildcards

### ISSUE THREAD

**Issue by inzmamon** [NAUbackup/VmBackup#20]
Would'n it be nice to be able to put the vm's names with wildcards into "exclude" variable?
I'd like to exclude all non-production vm's from backing up. I already named test and staging machines as "Snn-_" (staging) and "Xnn-_" (test ones) so I'd like to exclude them (14 in total) without specifying line by line...
When I use wildcards in the exclude variable, script exits with an error (as the vm hasn't been found).

**Comment by NAUbackup** [comment]
That is a good suggestion.  We will definitely take that under consideration. The other option is to include VMs more carefully with more specific wildcarded names.

If ever time permits it would be nice eventually to be ab;e to process REGEX expressions fully for both includes and excludes. :-)

**Comment by NAUbackup** [comment]
Currently, we are more focused on including VMs using a much more flexible regex mechanism, which should make exclusions a lot easier and not require them to be wildcarded.

**Comment by NAUbackup** [comment]
This feature will be appearing in the next release, which will support regex to both include and exclude VMs. :-)
