### ISSUE TITLE
Restore not working

### ISSUE THREAD

**Issue by GitZer0** [NAUbackup/VmBackup#23]
Backup is working fine (both SMB or NFS share).
When I try to restore a virtual machine with the following command: 

> xe vm-import filename=<VM-Name>.xva preserve=true 

I always receive this error:
_The server failed to handle your request, due to an internal error.  The given message may give details useful for debugging the problem.
message: INTERNAL_ERROR: [ Not_found ]_

This is the first time using NAUbackup, so I think the error is up to me, but I don't know what to do at the moment.
Version of XenServer is 7.0.0

Zero

**Comment by NAUbackup** [comment]
Zero,
The filename surely must be more than just ".xva"? The error message appears to indicate the file cannot be found, hence the name is incorrect or there is no such file. By default, it should create an XVA file using the VM name followed by the ".xva" file extension.
-=Tobias

**Comment by GitZer0** [comment]
Dear Tobias,

this was my fault.Of course there is a name for the VM. My VM's have names like Linux01, Linux02 and so on.
So my command is: xe vm-import filename=Linux01.xva preserve=true
Is this correct?

Zero

**Comment by GitZer0** [comment]
Dear Tobias,

I'm not totally sure why, but it is working now.
Thanks for your support!

Zero
