### ISSUE TITLE
Backup based on tags

### ISSUE THREAD

**Issue by AstainHellbring** [NAUbackup/VmBackup#25]
If there were a way to instead of backing up by name, backup based on tag that would make my process so much easier.  Any thoughts on that?

Thanks

**Comment by NAUbackup** [comment]
A tag would have to be associated with each server and kept somewhere in a DB of sorts, which would make maintenance a bit harde. We want to keep this very simple. I'd recommend instead a naming scheme that incorporates tags as part of your VM names, at least for now. We have also thought about creating VM groups with common characteristics, like the total number of backups retained.

**Comment by NAUbackup** [comment]
Instead, we are planning on soon introducing regex-based handling of groups of VMs to both include and exclude.
