### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by adrianomirandaa** [NAUbackup/VmBackup#28]
Hi everyone. I'm from Brazil and I don't speak English very well. So, I'm sorry for my poor English.

Well, I'm testing this wonderful tool and I'm having a little problem in a Virtual Machine:

"**UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 29: ordinal not in range(128)**"

I think that It is a problem with character in "VM description area", like "áéóãẽ" or "ñ". I already deleted all information on "description" area, but it still not working.

Can anyone help me?

Thank you.

**Comment by NAUbackup** [comment]
These are currently not supported -- just pure ASCII letters, digits, hypens and dashes. Host names should also not include any whitespace.
