### ISSUE TITLE
Exception on email sending when some backups are in "WARNING" state

### ISSUE THREAD

**Issue by rudolfmayer** [NAUbackup/VmBackup#31]
When there is a warning state in the backups, E-Mail sending fails with this exception

```
***ERROR EXCEPTION - exceptions.TypeError
***ERROR NOTE: see VmBackup output for details
Traceback (most recent call last): 
  File "/opt/VmBackup/VmBackup.py", line 1360, in ?
    main(session)
  File "/opt/VmBackup/VmBackup.py", line 440, in main
    send_email("%s 'WARNING VmBackup.py' %s" % (MAIL_TO_ADDR, STATUS_LOG))
TypeError: send_email() takes exactly 3 arguments (1 given)
```

The faulty statement seems to be in https://github.com/NAUbackup/VmBackup/blob/master/VmBackup.py#L440

**Comment by NAUbackup** [comment]
Thank you, Rudolf, for pointing this out. We will take a look ASAP.

**Comment by NAUbackup** [comment]
Have not heard further issues with this, and hence I am closing it for now.
