### ISSUE TITLE
Exclude VDI's.

### ISSUE THREAD

**Issue by deviousgeek** [NAUbackup/VmBackup#37]
Some of our virtual machines have VDI's that are used for scratch disks (tempoary files), or data that is not necessary to backup.

Is it possible to add an exclude option for VDI files so that these are not included in the backup process?

Kind Regards.

**Comment by NAUbackup** [comment]
Currently, we only support backing up the root VDI (device 0), which contains presumably just the operating system. One way to achieve what you want would be to clone the VM and delete any unwanted VDIs before backing it up.
