### ISSUE TITLE
Restore process

### ISSUE THREAD

**Issue by rmarksteffen** [NAUbackup/VmBackup#40]
I've combed the docs, and without finding specific examples and not wanting to wipe my current live VM, can someone explain how I would restore a backup to a "new" VM (and then I guess I could disable the network interface before I boot it so that it doesn't use the same statically configured IP address)?  I had a situation where I wanted to restore some files from a backup, but otherwise the production image was working fine.  (apologies if this is not the right forum to ask)

**Comment by davisko** [comment]
If you are using Xen Center, go to File -> Import to start the VM import wizard. It should be self-explanatory from there, unless you have special circumstances. The import wizard will let you choose a new VM name, storage location, networking, etc…

Kory Davis
