### ISSUE TITLE
Emails not being recieved

### ISSUE THREAD

**Issue by ilium007** [NAUbackup/VmBackup#45]
I missed emails due to SMTP server timeout. I have submitted a pull request that adds capability to retry the email send 3 times with a 5 sec delay. Feel free to modify as required but the patch works on my test system.

**Comment by NAUbackup** [comment]
I plan to test this out and if all looks good incorporate it into the next minor release update. Thank you for your contribution.
--Tobias

**Comment by NAUbackup** [comment]
The plan is to incorporate this into the next release, and thank you again. Sorry this is taking so long - I am currently having to take care of pretty much all of this and have had a number of major projects with high priorities preempting this.
--Tobias

**Comment by NAUbackup** [comment]
Incorporated into release V3.2.
