### ISSUE TITLE
Add option to delete old backups first

### ISSUE THREAD

**Issue by brgsousa** [NAUbackup/VmBackup#49]
Hi, when you set max_backups, it deletes the old backup after backing up the current one. Disk usage could be optimized by deleting old backups first and then backing up the current one. Think of VMs that have 500GB of disks.

**Comment by NAUbackup** [comment]
Hi... Thank you for your feedback. This is very deliberately done afterwards for if the backup should fail and you only have one to start with, you would end up with nothing. If the VM is corrupted and the backup fails, you would have no way at all then to recover it. You could of course manually delete it ahead of time by writing a separate script to be executed before the main backup script is kicked off via cron to take care of such exceptions, is what I'd suggest.

**Comment by brgsousa** [comment]
Thank you for your answer!
Your script is being very helpful at work, thank you!
