### ISSUE TITLE
Invalid charactes in MV Name or Description

### ISSUE THREAD

**Issue by dbaselica** [NAUbackup/VmBackup#56]
If name-label or name-description have invalid characters, the  process don't work

**For example**
name-label ( RW): MV067 - VPS1-2 - Soles Asociación Civil
name-description ( RW): MV067 - VPS1-2 - Soles Asociación Civil - Actualizada al 05/05/2015. 

2017-09-29-(00:17:50) - *** success: /var/run/sr-mount/bcfb7e87-cce2-af29-f45d-11cac15e7b05/MV007 - VPS5-6 - Coniferal/backup-2017-09-28-(23-42-55)/MV007 - VPS5-6 - Coniferal.xva.gz : 6G
2017-09-29-(00:17:50) - VmBackup vm-export MV007 - VPS5-6 - Coniferal - ***Success*** t:34
2017-09-29-(00:17:50) - *** vm-export begin MV008 - VPS3-4 - AdminDestefanis
2017-09-29-(00:17:50) - vm-export - vm_name: MV008 - VPS3-4 - AdminDestefanis max_backups: 2
2017-09-29-(00:17:51) - new backup_dir: /var/run/sr-mount/bcfb7e87-cce2-af29-f45d-11cac15e7b05/MV008 - VPS3-4 - AdminDestefanis/backup-2017-09-29-(00-17-51)
2017-09-29-(00:17:51) - Writing vm config file.
'ascii' codec can't encode character u'\xf3' in position 29: ordinal not in range(128)
2017-09-29-(00:17:51) - ***ERROR EXCEPTION - exceptions.UnicodeEncodeError
2017-09-29-(00:17:51) - ***ERROR NOTE: see VmBackup output for details

The 'name-description' only use in vm_out.write
But 'name-label' is used for Folder an Files... 

**Partial Solution....For 'name-description'**
552  # vm_out.write('name_description=%s\n' % vm_record['name_description'])
619  # vdi_out.write('name_description=%s\n' % vdi_record['name_description'])

**Partial Solution....For 'name-lable'**
Replace in Xen all invalid chars in MV Name 

**List or invalid chars for my...**
("á") ("é") ("í") ("ó") ("ú") ("ñ") ("/") ("\") (":") (")") ("(") (".") ...
But I think the only support ASCII 127 chars

**Deseable Solution...**
Automatically replace the invalid chars for "" or "_"
in Name or Description

**Comment by NAUbackup** [comment]
The issue is while XenServer support vaious ISO character formats internally, Linux gets unhappy when you try to create files with character sets that are pretty much anything beyond alphanumeric characters and a few symbols.  Honestly, the easiest "fix" would be to restrict VM names to just a limited character set.

**Comment by NAUbackup** [comment]
I think I have found a way to do a better job of making this work. For a descriptor string
I can get without errors an output file containing the VM "Descriptor" string:

XS66 schön schließen

and the resulting XML comes out as:

`                      <member>
                        <name>name_description</name>
                        <value>XS66 sch&#xF6;n schlie&#xDF;en</value>
                      </member>`

I can, in fact, capture the entire XML info. This still isn't going to help to be able to use it to re-create the settings within the VM, but at least it should be possible to capture the entire VM's metadata. :-)

-Tobias

**Comment by NAUbackup** [comment]
Creating a full export of all the VM metadata may be the way to go. See my blog at: https://xenserver.org/blog/entry/introduction-to-saving-vm-parameters-how-i-metadata-backup-1.html

**Comment by NAUbackup** [comment]
I have a version of this currently in test phase. Instead of a number of different metadata outputs, it all goes into one XML file.

**Comment by NAUbackup** [comment]
Now handled in V3.22.
