### ISSUE TITLE
Incremental or incremental backup why not?

### ISSUE THREAD

**Issue by aroldo-biz** [NAUbackup/VmBackup#57]
If the snapshots are incrementals the NAUbackup could also do incremental or differential backup.

What would be the biggest difficulties?

**Comment by NAUbackup** [comment]
This is not as easy as it looks, not so much from how to do it, but how to track each and every full and incremental backup, its history, dependencies, if some are deleted, etc. I honestly do not have the resources to think about how to tackle this at this point. Perhaps someone else does, in which case we'd of course consider incorporating that feature. One would also need to figure out a good structure in terms of subdirectory hierarchy and naming conventions how to hold all that information, as well as how to purge such data and records of VMs get deleted, moved, etc. To me at least, it seems not so trivial. I know that XenOrchestra supports this, but this is also in essence a commercial product.

**Comment by aroldo-biz** [comment]
Thinking better to do the way I thought I'd have to rewrite a new script.

I find the way I thought about doing it's not really easy because my premise may be wrong, so I ask:

Does Xenserver natively have the capability to export a child snapshot without exporting the parent snapshot?

Initial idea seemed simple to me.

We would use the Xenserver's own VM snapshot Schedule to manage the snapshots and the script would have the role to export these snapshots to the backup destination.

**Comment by NAUbackup** [comment]
Once you have a full snapshot, yes, you can create and export just the incremental snapshots. The scheduler is nice, but I am thinking more along the lines of disaster recovery where you lose all that information and hence want to be able to manage and track it all externally.  There is no reason to mix and do the main backups with VMbackup and the incrementals then via what you can automate within the XenServer native environment.

**Comment by aroldo-biz** [comment]
I agree, it is that I lack space to store some versions of the backup of my virtual machines. There's only room for a backup.

Thank you very much.

**Comment by NAUbackup** [comment]
I'm not 100% sure, but I recall reading that once a primary snapshot has been created you don't have to keep even all your incrementals on-line and possibly not even the initial snapshot, which could potentially save a lot of space.  I'd have to go back and read through the process again in detail.

In any case, I'm going to go ahead and close this for now and may possibly revisit this at some point in the future if the means to do this more efficiently should ever materialize.
