### ISSUE TITLE
Fix for non Unicode characters in vm_record['name_description']

### ISSUE THREAD

**Issue by AceMax** [NAUbackup/VmBackup#60]
Can I suggest that you add **.encode("utf-8")** to **vdi_out.write('name_description=%s\n' % vdi_record['name_description'])**

ex. 
**vdi_out.write('name_description=%s\n' % (vdi_record['name_description']).encode("utf-8"))**

This will fix issues with as in my case with Swedish characters in the VM descriptions.

br
//Max

**Comment by NAUbackup** [comment]
Hello, Max:
I will gladly look into it. Not this week, but hopefully next, I know it's a pretty small thing, but I'm totally swamped at the moment and even small changes require adequate testing.
Regards,
--Tobias

**Comment by AceMax** [comment]
Thanks!
No problem. I've been running with the "fix" for a while and everything is working great.

For your information, without converting the description string, the script exits with a exception error when there is non unicode characters present.
For me, this is the only string I have had to convert but it might be a god thing to make the scripts use utf-8 in general. 

br
//Max

**Comment by NAUbackup** [comment]
Hi, Max:
The VM description does come out encoded OK in the metadata for the VM already, correct? It's just the one occurrence where the name_label is output that needs UTF8 encoding, correct?
--Tobias

**Comment by AceMax** [comment]
Tobias,
Yes, that might be a good idea even though I guess the name_label usually reflects the hostname of the VM and I'm not sure you can use non unicode characters in host names (in Windows at least). 
Anyway. Better to be safe than sorry :)
//Max

**Comment by AceMax** [comment]
And for reference, here's what happens with the original v3.2:

Traceback (most recent call last):
  File "/backup/vmbackup/snapshots/NAUbackup/VmBackup.py", line 1466, in <module>
    main(session)
  File "/backup/vmbackup/snapshots/NAUbackup/VmBackup.py", line 336, in main
    vm_meta_status = gather_vm_meta(vm_object, full_backup_dir)
  File "/backup/vmbackup/snapshots/NAUbackup/VmBackup.py", line 563, in gather_vm_meta
    vm_out.write('name_description=%s\n' % vm_record['name_description'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 25: ordinal not in range(128)

In this case, u'\xe4' = ä
//Max

**Comment by NAUbackup** [comment]
We ran into an issue earlier with name_label entries that had special characters in them, hence changed the VM metadata backup completely. I'm in the process of testing the changes to name_label and name_description, which you correctly stated as being very minor.

**Comment by NAUbackup** [comment]
Max,
This addition has been incorporated into V3.22. Sorry, I meant to mention that in the release notes.

--Tobias
