### ISSUE TITLE
NameError: global name 'xvda_uuid' is not defined

### ISSUE THREAD

**Issue by 0sorkon** [NAUbackup/VmBackup#65]
[root@xen-hp380g8-a NAUbackup]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: XenServer
Description:    XenServer release 7.2.0 (xenenterprise)
Release:        7.2.0
Codename:       xenenterprise

[root@xen-hp380g8-a NAUbackup]# grep -v "#" ./vdi-backup.cfg
max_backups=3
backup_dir=/mnt/backup/nfs/Xen_backup/vdi
vdi_export_format=vhd
vdi-export=ceph.admin

[root@xen-hp380g8-a NAUbackup]# VmBackup.py ./passwd.file ./vdi-backup.cfg
...
2018-02-01-(17:12:11) - vbd: OpaqueRef:89be6584-318a-9a3a-de6d-d15bd1e78e91
2018-02-01-(17:12:11) - disk: 1 - begin
2018-02-01-(17:12:11) - vbd: OpaqueRef:42d033a2-d766-5767-212d-51a8af5809b1
2018-02-01-(17:12:11) - Writing VIF info
2018-02-01-(17:12:11) - Writing VIF: 0
global name 'xvda_uuid' is not defined
2018-02-01-(17:12:11) - ***ERROR EXCEPTION - <type 'exceptions.NameError'>
2018-02-01-(17:12:11) - ***ERROR NOTE: see VmBackup output for details
Traceback (most recent call last):
  File "/mnt/backup/nfs/Xen_backup/NAUbackup/VmBackup.py", line 1491, in <module>
    main(session)
  File "/mnt/backup/nfs/Xen_backup/NAUbackup/VmBackup.py", line 177, in main
    if xvda_uuid == '':
NameError: global name 'xvda_uuid' is not defined

**Comment by NAUbackup** [comment]
Thank you for reporting this -- will take a look. Which VMbackup release version exactly are you running?

**Comment by 0sorkon** [comment]
latest from github v3.22 2017/11/11.
on 3.21 september 2017 everything working well.

**Comment by NAUbackup** [comment]
Might be due to a change in a library definition. That it worked on 3.21 and not on 3.22 is very helpful to know, thank you.

**Comment by NAUbackup** [comment]
I think the issue is that the global variables xvda_uuid and xvda_name_label are still needed under certain circumstances, but were commented out when going from 2.21 to 3.22:

560,561c552,553
< #    global xvda_uuid
< #    global xvda_name_label
---
>     global xvda_uuid
>     global xvda_name_label

Please try to remove the "#" from the lines from VmBackup.py where those two variables are commented out and see if the script then runs correctly.

--Tobias

**Comment by 0sorkon** [comment]
yes, after uncommenting line 560,561 ```
global xvda_uuid
global xvda_name_label
``` it seems working

**Comment by NAUbackup** [comment]
OK, good, thank you. I will make that correction as well as a couple of other minor adjustments and get a new release out in the near future. Glad it's working for you again!
--Tobias
