### ISSUE TITLE
Impossible to send email notification

### ISSUE THREAD

**Issue by Romu007** [NAUbackup/VmBackup#71]
Hello all, 

i recently downloaded your script to backup my VMs and thanks a lot for your work. 

But when I'm trying to configure the mail notification, i have this error at the end of the script : 

Exception: socket.error -  (97, 'Address family not supported by protocol')

Do you have any idea please ? 

Thanks a lot for your help 
Romu

**Comment by Romu007** [comment]
le output log : 

Exception: socket.error -  (97, 'Address family not supported by protocol')
Exception: socket.error -  (97, 'Address family not supported by protocol')
^C
2018-04-21-(11:00:27) - ***ERROR EXCEPTION - exceptions.KeyboardInterrupt
2018-04-21-(11:00:27) - ***ERROR NOTE: see VmBackup output for details
Traceback (most recent call last):
  File "/home/XenServer-SDK/XenServerPython/backup_test.py", line 1495, in ?
    main(session)
  File "/home/XenServer-SDK/XenServerPython/backup_test.py", line 490, in main
    send_email(MAIL_TO_ADDR,'WARNING VmBackup.py', status_log)
  File "/home/XenServer-SDK/XenServerPython/backup_test.py", line 877, in send_email
    s = smtplib.SMTP(MAIL_SMTP_SERVER)
  File "/usr/lib/python2.4/smtplib.py", line 244, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.4/smtplib.py", line 297, in connect
    self.sock.connect(sa)
  File "<string>", line 1, in connect
KeyboardInterrupt

**Comment by NAUbackup** [comment]
Hi, Romu... Did you look at the README file as to an example of how and where to define the SMPT mail server? What have you put in? Is that mail server even reachable from your XenServer host (you can try to telnet to port 25 of it as a test)?
Regards,
--Tobias

**Comment by AlBundyLoves69** [comment]
Hi, does this help you?

**Comment by AlBundyLoves69** [comment]
Does this help you?

[MCVE for email check](https://github.com/NAUbackup/VmBackup/issues/74)

**Comment by Romu007** [comment]
Hello guys, 

it seems that i can't use SSL with the version of my python 

# python
Python 2.4.3 (#1, Sep 21 2011, 20:06:00) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-51)] on linux2

i have to update the python's version .

Do you have any other idea ? 

Also, Albundy, i have an error when i'm trying to send with your link : 

python testmailromu.py 
Traceback (most recent call last):
  File "testmailromu.py", line 94, in ?
    send_email('romuald.bouvard@hotmail.fr', 'Test-Email VmBackup.py', status_log)
  File "testmailromu.py", line 90, in send_email
    print("Exception: SMTPException - %s" %e.message)
AttributeError: SMTPServerDisconnected instance has no attribute 'message'

**Comment by NAUbackup** [comment]
There should be a much newer version on your XenServer -- 2.7.5 on XS 7.X which runs the Linux kernel 4.4.0.  What version of XenServer is this? Back before early version os XS 6.X, this script is not going to work as it requires a reasonable new version of python to run, so your suspicious is probably correct.

**Comment by AlBundyLoves69** [comment]
Look Romu007,

I am not a Python programmer. I extracted the test script from the existing `VmBavkup.py` in order I can find out **very convenient** the correct SMTP settings for my Exchange server and test, if it does accept the relay.

Now, it is **your** task to play around and sort everything out. The script works and when you get errors you have to comment/uncomment/edit the 4 lines until you receive an email. Sorry, I can't do more fore you.

**Comment by NAUbackup** [comment]
I am closing this thread.
