### ISSUE TITLE
Feature request: Display hostname in the email

### ISSUE THREAD

**Issue by AlBundyLoves69** [NAUbackup/VmBackup#75]
I have several XenServer hosts and it would be nice when in the email subject sent after the job finished would be add the result of `hostname`. For the moment I added it in my local version.

**Comment by AlBundyLoves69** [comment]
I mean in the subject of the email. I would have here directly the code lines:

Line #483:
`            #send_email(MAIL_TO_ADDR, 'ERROR ' + os.uname()[1] + ' VmBackup.py', status_log)`

Line #490
`            #send_email(MAIL_TO_ADDR,'WARNING ' + os.uname()[1] + ' VmBackup.py', status_log)`

Line #497:
`            #send_email(MAIL_TO_ADDR, 'Success ' + os.uname()[1] + ' VmBackup.py', status_log)`

**Comment by NAUbackup** [comment]
I can probably build that into the next release. We run a custom version in-house that already has that built in, hence I can appreciate having that in the email header.

**Comment by NAUbackup** [comment]
Coming in the next release (3.23).
