### ISSUE TITLE
Excluding a VDI from backup

### ISSUE THREAD

**Issue by AlBundyLoves69** [NAUbackup/VmBackup#76]
Sorry for bothering you with this question:

Is it possible to exclude some VDIs from the backup? Some VDIs are huge and used for log files and it doesn't make a sense to include them in the backup.
I don't understand the configuration file:

```
# special vdi-export - only backs up first disk. See README Documenation!
#vdi-export=my-vm-name
```

What does it mean? How can I use it?

For example, I would append `#NB` [_NoBackup_] to the VDI names which don't need a backup. Is there a way to exclude these VDIs with a regexp like  `*#NB`?

Thank you very much.

**Comment by NAUbackup** [comment]
Yes, the same syntax applies for includes and excludes for VDI exports as for full VM exports. There are examples given in the README file or if that's confusing, give me a specific case and I can help come up with the proper syntax.

**Comment by AlBundyLoves69** [comment]
I would like to exclude all VDI's which contain this string: `#NB` - these means, what I have to set it like this:

`exclude=*#NB` and this will apply to VM and VDI as well?

**Comment by NAUbackup** [comment]
Excludes need to be set up separately for VDIs and for VMs. They are not mutually inclusive or exclusive.

**Comment by AlBundyLoves69** [comment]
I am really very sorry but somehow I don't get it. How should be the line in the config file which excludes all VDIs which have `#NB` in their name?

**Comment by NAUbackup** [comment]
exclude=.*#NB

should work, unless you need to escape that special character. This would exclude all VMs as well.

**Comment by NAUbackup** [comment]
This diagram above helps a lot, because I think you are maybe not understanding the current function of the exclude option. It does _not_ apply to the labels of the VDIs, only to the names of the actual VMs. You can only apply this filter to the names of VMs, not to the individual VDIs.

**Comment by NAUbackup** [comment]
Closing this for now. Re-open later, if needed. Try again under 3.24 as it has some bug fixes that were incorporated and might be related.
