### ISSUE TITLE
Feature request: Selection WHEN old backup has to be deleted

### ISSUE THREAD

**Issue by AlBundyLoves69** [NAUbackup/VmBackup#77]
_What is the problem:_

Now, the old backups are removed according to the `max_backups=` setting **AFTER** a backup has been done.
This means that I need - especially - for very large VMs extra space because `max_backups + 1` versions of one VM do exists for a short time.

_What I would suggest:_
A setting like `remove_version_before_backup` which can be `0` or `1`. `1`means that the old version would be removed **BEFORE** the backup starts and this would _relax_ some situations.

**Comment by NAUbackup** [comment]
Might be hard to fit in the logic to accomplish this as the code is already pretty convoluted. The other option would be to write a separate task that is run by cron before the backup is run that takes the list of VMs, finds the oldest version of the backup, and deletes that directory.

**Comment by AlBundyLoves69** [comment]
I don't know but as I see the source code the _clean up_ is processed in the `final_cleanup` function. Shouldn't be enough to call this function - and may be adapt it a bit - **before** the backup for the VM starts according the new setting?

I understand the intention using `cron` but this splits the whole procedure into several tasks and the question is if it is a good solution.

**Comment by NAUbackup** [comment]
I'll take another look when I can focus on that piece a bit more. Am already working on other pieces and don't want to get spread too thinly.

**Comment by AlBundyLoves69** [comment]
OK Tobias, due to the fact last night I ran out again of space I wrote now this morning this short bash script. It runs only on XenServer 7.x

As you suggested, it is running as a separate task and should be executed by cron 1 minute **before** your backup script is running. It respects the `backup_dir`  and `max_backups` settings.

Due to the fact it deletes the old directories your script will never find anything to delete. Enjoy it until you may have implemented the clean up **before** the backup runs.

This script has commented the `rm` command. Remove the `# ` comment sign when running for real.
I am not the bash professional so may be some string operations could be simplified - but it works how it is now.

```
#!/bin/bash
#
# RemoveOldestBackup.sh - a VmBackup.py add on
#    1) Removes the oldest backup BEFORE VmBackup.py starts.
#    2) Run it via cron job 1 minute before VmBackup.py starts.
#    3) Set the path to the VmBackup.cfg file in VmBackupPath.
#    4) This script respects the <max_backups> <backup_dir> settings as set in hte configuration file.
#    5) No modifications needed for VmBackup.py - it won't just delete any directory in the <final_cleanup> function.
#
# known issues: max_backups cannot be 0
#
# Written by Peter VARGA, Version 1.00.20180602
# Tested on XenServer 7.4
# I don't think it runs on XenServer 6.x
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# the path to VmBackup.cfg - must be set
VmBackupPath=/scripts/VmBackup.cfg

getSetting ()
{
    # get the position of the '=' sign from the <requested setting>
    positionOfEqualSign=$((`grep -E "^$1=" $VmBackupPath | grep -ob '=' | grep -Eo '[0-9]+'` + 2))

    # get now the value and remove some possible leading white spaces
    settingValue=`grep -E "^$1=" $VmBackupPath | cut -c $positionOfEqualSign- | awk '{$1=$1};1'`

    # return it now to the caller
    echo $settingValue
}

createSeparator()
{
    string=$1
    length=${#string}
    echo `seq -s- $length | tr -d '[:digit:]'`
}

backupDir=$(getSetting "backup_dir")
maxBackups=$(getSetting "max_backups")

if [ "$maxBackups" -eq 0 ]
then
    echo "max_backups=0 not supported"
    exit 1
fi

logString="Found backup directory in $backupDir. Processing now each backup and keeping $maxBackups versions."
separator=$(createSeparator "$logString")
printf  "%s\n%s\n%s\n" $separator "$logString" $separator

echo
df -h $backupDir

# iterate through all directories found in the backup path
for currentVM in `ls $backupDir`
do
    # 1) get all backups for this vm.
    # 2) get the most <max_backups> backups.
    # 3) assure the path is correct and remove possible multiple / in the path - comming from "dirty" backup_dir setting.
    # 4) prepare it with sed for the grep command in order these most current directories are NOT deleted
    # 5) join all lines into 1 line
    keepingDirectories=`ls -d -t -1 $backupDir/$currentVM/* | head -$maxBackups | xargs readlink -m | sed -e 's/^/-e /' | paste -sd " " -`
    separator=$(createSeparator "$backupDir/$currentVM:")
    echo $separator
    echo -e "$backupDir/$currentVM:\n    Keeping [$keepingDirectories]"

    # process each backup directory in the VM backup
    for currentBackupDirectory in `ls -d1 $backupDir/$currentVM/* | grep -v $keepingDirectories`
    do
        echo "    Deleting: $currentBackupDirectory"
#        rm -R -f $currentBackupDirectory
    done
done

echo "................................................"
df -h $backupDir
```

**Comment by NAUbackup** [comment]
Hi, Peter:
One desired thing would be to check if the current existing backup count is already less than or equal to "MAXBACKUPs -1" so that if run multiple times, you don't end up unintentionally deleting all your backups for any VM. Let me think about this a bit more and see how much work it would be to incorporate this as an option. It would involve adding an extra parameter and a pre-check as well as a post-check to make sure any erasing of older backups is performed at the right time.
--Tobias

**Comment by AlBundyLoves69** [comment]
Thank you for this hint. In my case the script just crashed because I passed it to `head` as parameter. I fixed it in the above source code.

It crashed with this error: `head: unrecognized option '--1'`

**Comment by NAUbackup** [comment]
Making pretty good progress on this running with the token pre_clean=True. Currently testing and refining various stages of the process.
--Tobias

**Comment by NAUbackup** [comment]
Pretty much done with this and am planning to upload to the beta area soon. Stay tuned.

**Comment by NAUbackup** [comment]
@AlBundyLoves69 / Peter: No comments, feedback, ...?

**Comment by AlBundyLoves69** [comment]
Sorry Tobias, I am currently a but under pressure. I am going to test it this weekend and then I give you my feedback! Looking already forward testing to the new features.

**Comment by AlBundyLoves69** [comment]
Tobias, I was now checking the new version 3.23 but I am a bit confused. In the source the is only one appearance of `pre_check` in the comment and in lines 1348 there is missing the text for the new option.

It looks like in the available source the code for pre_check is somehow missing. At least the command line option is never evaluated. Or am I blind?

**Comment by NAUbackup** [comment]
Hi, Peter... let me check what's up -- it was working fine and now I'm also getting this error message.

**Comment by NAUbackup** [comment]
Argh!!!  The parameter is pre_clean (not pre_check!). So sorry. I will update the code comments and READ me file to reflect this. I had to change it to avoid conflict with another variable name. Again, my apologies.  It should run as is fine if you use pre_clean=True.

**Comment by NAUbackup** [comment]
I just pushed updates to correct that issue. Thanks for your patience.

**Comment by AlBundyLoves69** [comment]
Yes Tobias. It looks very good. It seems to work. I am using - _on my own risk [but I trust you :-)]_ - the current 3.23 version.

**Comment by NAUbackup** [comment]
Thank you, Peter! Believe me, I tested this many, many times with real VMs using a lot of different combinations to make sure all cases I could think of were handled properly. You could of course also split your VMs into different groups and run one set with pre_clean where it matters and not use the feature with the other VMs that have a separate configuration file. I thought about tagging each VM individually, but this would have been much more complicated to implement.

**Comment by AlBundyLoves69** [comment]
It is perfect how it is now implemented! Tagging each VM individually would be lot of work and I think that it is not really needed! Nice hint regarding grouping it...

**THANK YOU very much!**

Have a nice weekend.

**Comment by NAUbackup** [comment]
Same to you and please report any issue you might encounter. Appreciate your helping to test this out, Peter.
--Tobias

**Comment by AlBundyLoves69** [comment]
After additional 3 weeks using the new feature on 2 hosts I am convinced I can confirm, it works without any bug. The _pre-clean_ is deleting the oldest version correctly so - in my case - there is enough space for the newest set.

**Comment by NAUbackup** [comment]
Nice to hear, Peter!
--Tobias
