### ISSUE TITLE
email send is not working

### ISSUE THREAD

**Issue by petrsvacina** [NAUbackup/VmBackup#8]
Hi, I Hope I configured sending mail correctly, but not working for me: 

send_email() takes exactly 3 arguments (1 given)
2015-02-23-(12:03:25) - ***ERROR EXCEPTION - exceptions.TypeError
2015-02-23-(12:03:25) - ***ERROR NOTE: see VmBackup output for details
Traceback (most recent call last):
  File "VmBackup.py", line 707, in ?
    main(session)
  File "VmBackup.py", line 368, in main
    send_email("%s 'Success VmBackup.py' %s" % (MAIL_TO_ADDR, STATUS_LOG))
TypeError: send_email() takes exactly 3 arguments (1 given)

**Comment by NAUbackup** [comment]
Sorry for the response delay, I assume you resolved this. If not post back with additional info.

**Comment by Bendolfc** [comment]
I am having the same issue, have filled in the 3 variables and removed the comments in the appropriate places, can't see anything obvious as to why it isn't working.

**Comment by sylk4** [comment]
I had exact the same issue. I solved it with a patch:
https://github.com/codedmind/VmBackup/commit/0d6960e84adafe83ab16346095d94994d3237009

**Comment by Bendolfc** [comment]
Thanks, that worked, saved me a bit of time figuring out what was wrong.
