### ISSUE TITLE
vdi-export failure under XenServer 7.5

### ISSUE THREAD

**Issue by NAUbackup** [NAUbackup/VmBackup#83]
I have heard of at least one report of vdi-export failing under XenServer 7.5 with the error message:

Error code: VDI_IO_ERROR
Error parameters: Device I/O errors 

Has anyone else seen this? The concern is that vdi-export/vdi-import has never really been officially supported by Citrix and may be broken in XenServer 7.5 and beyond.

Am testing from the command line and it seems to be work OK for me on a XS 7.5 server.

--Tobias

**Comment by NAUbackup** [comment]
Seems to be a bug in XenServer itself; see https://bugs.xenserver.org/browse/XSO-868

**Comment by cbelanger** [comment]
Not the first time a new Xenserver version broke something that was working previously.  I hope that there is going to be a fix very soon.

Thanks for the update!

**Comment by NAUbackup** [comment]
You bet!

**Comment by Slapbox** [comment]
Does NAUbackup work with Xenserver 7.5 for most people, or is it broken for most people?

**Comment by NAUbackup** [comment]
This issue will supposedly be addressed in the next XS release.

**Comment by Slapbox** [comment]
Thanks for your reply @NAUbackup. I did see that, but I'm being pushed to implement backups at my organization. Is NAUbackup working for anyone that we know of on 7.5? If not, I'll have an easier time selling the idea of waiting for XenServer 7.6.

**Comment by NAUbackup** [comment]
Many thanks, @cbelanger , for checking out the functionality and temporary fix!

-=Tobias

**Comment by Slapbox** [comment]
@NAUbackup and @cbelanger thanks very much to both of you!

**Comment by NAUbackup** [comment]
Excellent news, and thank you for testing this and reporting back your findings, @Christian.

-=Tobias

**Comment by NAUbackup** [comment]
Closing this issue. It has been fixed in the XenServer 7.6 release.
