### ISSUE TITLE
Is NAUbackup compatible with XCP-ng?

### ISSUE THREAD

**Issue by blu-IT** [NAUbackup/VmBackup#89]
Hello,

is somebody here who has experience with NAUbackup script an the rocking **XCP-ng** v.7.6 ( https://xcp-ng.org/ )?
There will also be a new compression in the future https://xcp-ng.org/blog/2018/12/19/zstd-compression-for-xcp-ng/ and I would like to know if somebody here has already used NAUbackup with XCP.

Thanks!

Regards

**Comment by NAUbackup** [comment]
It partly depends on what pieces you're talking about. The XVA export format is pretty universal, for example, as should in principle be the metadata. For VMs, I'd guess probably, but this is probably a good question to post on the xcp-ng forum.

**Comment by lancefogle** [comment]
@blu-IT XCP-ng uses XAPI and the CLI for it (xe) underneath just like XenServer so there is no difference at all when it comes to the methods used by NAUBackup. Even the new compression that is being added to XAPI (and XCP-ng) is being added in a backwards compatible manner so it doesn't break anything in this script nor [OnyxBackupVM](https://github.com/onyxfireinc/onyxbackupvm)

**Comment by blu-IT** [comment]
Hi, thanks for your feedback! 

I will try and report my experience with that ;-)
