### ISSUE TITLE
Since last update the email notification contains the whole history

### ISSUE THREAD

**Issue by VARGA-Peter** [NAUbackup/VmBackup#98]
As the title already says it, since the update to the latest update the email notification regarding the result of the current backup process contains the whole history of all previous backups.

What am I doing wrong? I would like to have only the status of the current backup process.

**Comment by NAUbackup** [comment]
I am not sure, Peter. That seems odd.

I have to unfortunately announce that meanwhile, I have officially retired from NAU and no longer have access to the XS environment nor do I have access to any other test environment. I'm not sure at this point if anyone else will be taking on any sort of support.

**Comment by VARGA-Peter** [comment]
oh, this is very surprising. Sorry to hear that. I will debug the script and post here my result, but this may take a while...

**Comment by NAUbackup** [comment]
Yeah, sorry. It took place somewhat earlier than I had anticipated and under circumstances that are best left not discussed.

**Comment by VARGA-Peter** [comment]
I solved it very simple:
Your script is called within a shell script and once the backup finished I run this command:

`mv /snapshots/NAUbackup/status.log /snapshots/NAUbackup/status-``date "+%Y-%m-%d"``.log`

Now each email contains only the log for the current backup.

PS: I don't know how to escape in this editor the character for code so I used it twice but the real command has it only once surrounding `date`
